---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.SGMR_SERVICE_NAME}}"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 33%
      maxSurge: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      name: "{{.SGMR_SERVICE_NAME}}"
  template:
    metadata:
      labels:
        name: "{{.SGMR_SERVICE_NAME}}"
    spec:
      containers:
      - name: frontend
        image: "{{.SGMR_SERVICE_IMAGE}}:{{.SGMR_SERVICE_TAG}}"
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 100
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 500Mi
        ports:
          - name: frontend
            containerPort: {{.SGMR_SERVICE_PORT}}
        env:
          - name: SGMR_DATA_API_BASE_URL
            value: {{.SGMR_DATA_API_BASE_URL}}
          - name: SGMR_MAINTENANCE
            value: {{.SGMR_MAINTENANCE}}
          - name: GOV_NOTIFY_SUPPORT_EMAIL
            value: {{.GOV_NOTIFY_SUPPORT_EMAIL}}
      - name: proxy
        image: "{{.NGINX_IMAGE}}:{{.NGINX_TAG}}"
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        resources:
         limits:
          memory: "1024Mi"
          cpu: "1000m"
         requests:
          memory: "1024Mi"
          cpu: "1000m"
        env:
          - name: PROXY_SERVICE_HOST
            value: 'http://127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: "{{.SGMR_SERVICE_PORT}}"
          - name: SERVER_CERT
            value: "/certs/tls.crt"
          - name: SERVER_KEY
            value: "/certs/tls.key"
          - name: LOG_FORMAT_NAME
            value: 'json'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
          - name: STATSD_METRICS
            value: "FALSE"
        ports:
          - name: https
            containerPort: 10443
        volumeMounts:
          - name: certs
            mountPath: /certs
      volumes:
      - name: certs
        secret:
          secretName: "{{.SGMR_SERVICE_NAME}}-pod-cmio"
          
